# Generated by Django 3.1.3 on 2020-11-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201117_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
